# Generated by Django 2.2.5 on 2019-09-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=200)),
                ('foodcategory', models.CharField(max_length=200)),
                ('nutriscore', models.IntegerField()),
            ],
        ),
    ]
