# Generated by Django 2.2.6 on 2019-10-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbohydrates_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturated_fat_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar_100g',
            field=models.FloatField(default=0),
        ),
    ]
