# Generated by Django 2.2.6 on 2019-10-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0002_auto_20191024_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='none', max_length=200, unique=True),
        ),
    ]
