# Generated by Django 2.2.6 on 2019-10-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0003_auto_20191024_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='none', max_length=200, unique=True),
        ),
    ]
