# Generated by Django 2.2.6 on 2019-10-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0004_auto_20191025_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='food_category',
            old_name='food_id',
            new_name='food',
        ),
        migrations.AlterField(
            model_name='food',
            name='nutriscore',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
