import openfoodfacts
from fooddb.models import Food, Category, Food_category

list_of_categories = [
        'fr:Saucissons',
        'fr:Pâtes à tartiner',
        'fr:Comté',
        'fr:Charcuteries diverses',
        'fr:Jambons crus',
        'fr:Saucissons secs',
        'fr:Charcuteries cuites',
        'fr:Fromages blancs',
        'fr:miels-de-fleurs',
        'fr:Chipolatas',
        'fr:thons-a-l-huile',
        'fr:Boudins',
        'fr:Rillettes de volaille',
        'fr:Eaux-de-vie',
        'fr:purees',
        'fr:Jambons Serrano',
        'fr:Aiguillettes de poulet',
        'fr:Poulets panés',
        'fr:Reblochons',
        'fr:Allumettes de porc',
        'fr:Bloc de foie gras',
        'fr:Biscuits apéritifs soufflés',
        'fr:Miels d\'acacia',
        'fr:thons-a-l-huile-d-olive',
        'fr:Boudins blancs',
        'fr:produits-labellises',
        'fr:Tuiles salées',
        'fr:Quenelles',
        'fr:Filets d\'anchois marinés',
        'fr:Brownies',
        'Tomme',
        'fr:Fruits à coque salés',
        'fr:Filets d\'anchois marinés à l\'huile végétale',
        'fr:Céréales préparées',
        'fr:Morbiers',
        'fr:Faisselles',
        'fr:Saucissons secs pur porc',
        'fr:Ratatouilles',
        'fr:Fromages blancs natures',
        'fr:Crèmes dessert chocolat',
        'fr:Crèmes fraîches',
        'fr:Rillettes de viande rouge',
        'fr:chorizos',
        'fr:Rillettes de porc',
        'fr:Galettes à la frangipane',
        'fr:petits-beurres',
        'fr:Raclettes',
        'fr:Cordons bleus',
        'fr:Thons à l\'huile de tournesol',
        'fr:Côtes du Rhône',
        'fr:Miels crémeux',
        'fr:Brioches au chocolat',
        'fr:Crêpes de froment',
        'fr:Roqueforts',
        'fr:Bûches glacées',
        'fr:Poêlées',
        'fr:Yaourts sur lit de fruits',
        'fr:Biscuits apéritifs soufflés à base de maïs',
        'fr:aliments-a-base-de-plantes-seches',
        'fr:Pruneaux d\'Agen',
        'fr:Galettes de blé noir',
        'fr:Riz préparés',
        'fr:Fromages du Nord-Pas-de-Calais',
        'fr:Mimolettes',
        'fr:Pavés de saumon',
        'fr:escalopes-de-dinde-panees',
        'fr:palmiers',
        'fr:Saucisses sèches',
        'fr:Brandades de morue parmentière',
        'fr:Rosettes',
        'fr:Merguez',
        'fr:Nonnettes',
        'fr:Brioches pur beurre',
        'fr:escalopes-de-dinde-marinees-a-la-milanaise',
        'fr:produits-aoc',
        'fr:Crèmes entières',
        'fr:Brioches tranchées',
        'fr:confits-d-oignons',
        'fr:Desserts lactés aux œufs',
        'fr:Choucroutes garnies',
        'fr:Charcuteries à cuire',
        'fr:Coquillettes',
        'fr:Mousses de foies',
        'fr:Foies gras mi-cuits',
        'fr:Beaufort',
        'fr:Pâtes brisées',
        'fr:souris-d-agneau',
        'fr:Œufs en chocolat creux',
        'fr:Rôtis de porc',
        'fr:Tapenades noires',
        'fr:Ravioles',
        'fr:Mozzarella di Bufala Campana',
        'fr:Blinis',
        'fr:Crèmes dessert vanille',
        'fr:Cantal',
        'fr:Vinaigrettes allégées en matières grasses',
]

fc_list = []

pre_filled_fc_list = [
        ('Chorizo fort', 'fr:saucissons'),
        ('Chorizo fort', 'fr:chorizos'),
        ('Minis saucissons à picorer', 'fr:saucissons'),
        ('Minis saucissons à picorer', 'fr:saucissons-secs'),
        ('Minis saucissons à picorer', 'fr:saucissons-secs-pur-porc'),
        ('Mini saucisson sec pur porc', 'fr:saucissons'),
        ('Mini saucisson sec pur porc', 'fr:saucissons-secs'),
        ('Mini saucisson sec pur porc', 'fr:saucissons-secs-pur-porc'),
        ('Mini saucisson sec pur porc', 'fr:mini-saucissons-secs'),
        ('Le Saucisson Sec Nature', 'fr:saucissons'),
        ('Le Saucisson Sec Nature', 'fr:saucissons-secs'),
        ('Le Saucisson Sec Nature', 'fr:saucissons-secs-pur-porc'),
        ('Les Mini Bûchettes Noisettes', 'fr:saucissons'),
        ('Les Mini Bûchettes Noisettes', 'fr:saucissons-secs'),
        ('Les Mini Bûchettes Noisettes', 'fr:saucissons-secs-aux-noisettes'),
        ('Véritable saucisson sec', 'fr:saucissons'),
        ('Véritable saucisson sec', 'fr:saucissons-secs'),
        ('Saucisson sec', 'fr:saucissons'),
        ('Saucisson sec', 'fr:saucissons-secs'),
        ('Saucisson sec', 'fr:saucissons-secs-pur-porc'),
        ('mini saucissons secs piment', 'fr:saucissons'),
        ('mini saucissons secs piment', 'fr:saucissons-secs'),
        ('mini saucissons secs piment', 'fr:saucissons-secs-au-piment'),
        ('mini saucissons secs piment', 'fr:saucissons-secs-au-piment-d-espelette'),
        ('Saucisson le haute loire', 'fr:saucissons'),
        ('Saucisson le haute loire', 'fr:saucissons-secs'),
        ("Saucisson sec d'Ardèche", 'fr:saucissons'),
        ("Saucisson sec d'Ardèche", 'fr:saucissons-secs'),
        ("Saucisson sec d'Ardèche", 'fr:saucissons-secs-pur-porc'),
        ("P'tits saucissons secs", 'fr:saucissons'),
        ("P'tits saucissons secs", 'fr:saucissons-secs'),
        ("P'tits saucissons secs", 'fr:saucissons-de-boeuf'),
        ('Miche au poivre (6 tranches)', 'fr:saucissons'),
        ('Miche au poivre (6 tranches)', 'fr:saucissons-secs'),
        ("Saucisson sec à l'Ancienne", 'fr:saucissons'),
        ("Saucisson sec à l'Ancienne", 'fr:saucissons-secs'),
        ('Saucisson Sec', 'fr:saucissons'),
        ('Saucisson Sec', 'fr:saucissons-secs'),
        ('Saucisson Sec', 'fr:saucissons-secs-pur-porc'),
        ('Mortadella Bologna I.G.P.', 'fr:charcuteries-cuites'),
        ('Véritables Andouillettes De Troyes', 'fr:charcuteries-cuites'),
        ('Véritables Andouillettes De Troyes', 'fr:andouillettes'),
        ('Véritables Andouillettes De Troyes', 'fr:andouillettes-de-troyes'),
        ('Le petit tranché au fromage', 'fr:charcuteries-cuites'),
        ('Assortiment de Charcuteries alsaciennes', 'fr:charcuteries-cuites'),
        ('Blanc de poulet Qualité Standard (4 Tranches)', 'fr:charcuteries-cuites'),
        ('Blanc de poulet doré au four -25% de sel*- 2tr', 'fr:charcuteries-cuites'),
        ('Mortadelle', 'fr:charcuteries-cuites'),
        ('Jambon de Dinde (4 tranches)', 'fr:cordons-bleus'),
        ('Blanc de poulet doré au four - 4 tr', 'fr:charcuteries-cuites'),
        ('Mortadella Bologna IGP', 'fr:charcuteries-cuites'),
        ('Blanc de dinde  doré au four - 25% de sel*- 4 tr', 'fr:charcuteries-cuites'),
        ('Blanc de dinde  doré au four - 25% de sel*- 4 tr', 'fr:meta-categorie'),
        ('Blanc de poulet Fumé', 'fr:charcuteries-cuites'),
        ('Dés de Jambon', 'fr:meta-categorie'),
        ('Fromage blanc fondu', 'fr:gouter'),
        ('Gervita Nature', 'fr:fromages-blancs'),
        ('Gervita Nature', 'fr:fromages-blancs-natures'),
        ('Fromage Blanc au Lait de Brebis', 'fr:fromages-blancs'),
        ('Fromage Blanc au Lait de Brebis', 'fr:fromages-blancs-au-lait-de-brebis'),
        ('Fromage Blanc au Lait de Brebis', 'fr:fromages-blancs-natures'),
        ('Fromage Blanc Nature', 'fr:fromages-blancs'),
        ('Fromage Blanc Nature', 'fr:fromages-blancs-natures'),
        ('Fromage blanc nature 0%', 'fr:fromages-blancs'),
        ('Fromage blanc nature 0%', 'fr:fromages-blancs-natures'),
        ('Le Fromage Blanc', 'fr:fromages-blancs'),
        ('All I Want', 'fr:fromages-blancs'),
        ('All I Want', 'fr:fromages-blancs-aux-fruits'),
        ('Fromage blanc 3,3% 8 pots', 'fr:fromages-blancs'),
        ('Fromage blanc 3,3% 8 pots', 'fr:fromages-blancs-natures'),
        ('Fromage blanc', 'fr:fromages-blancs'),
        ('Fromage blanc', 'fr:fromages-blancs-natures'),
        ('Fromage blanc gervita nature', 'fr:fromages-blancs'),
        ('Fromage blanc gervita nature', 'fr:fromages-blancs-natures'),
        ('Fromage Frais aux Fruits 2% M.G.', 'fr:fromages-blancs'),
        ('Fromage Frais aux Fruits 2% M.G.', 'fr:fromages-blancs-aux-fruits'),
        ('Fromage Blanc Battu', 'fr:fromages-blancs'),
        ('Fromage Blanc Battu', 'fr:fromages-blancs-au-lait-de-vache'),
        ('Fromage Blanc Battu', 'fr:fromages-blancs-natures'),
        ('Fromage blanc Printiligne (0% MG)', 'fr:fromages-blancs'),
        ('Fromage blanc Printiligne (0% MG)', 'fr:fromages-alleges'),
        ('Calin Extra', 'fr:fromages-blancs'),
        ('Calin Extra', 'fr:fromages-blancs-natures'),
        ('Atún claro oliva', 'fr:thons-a-l-huile'),
        ('Atún claro oliva', 'fr:thons-a-l-huile-d-olive'),
        ('Atún claro en aceite de oliva', 'fr:thons-a-l-huile'),
        ('Atún claro en aceite de oliva', 'fr:thons-a-l-huile-d-olive'),
        ('Atún claro en aceite de girasol', 'fr:thons-a-l-huile'),
        ('Atún claro en aceite de girasol', 'fr:thons-a-l-huile-de-tournesol'),
        ('Rillettes de Poulet Rôti en Cocotte (+ 10 % Gratuit)', 'fr:rillettes-de-volaille'),
        ('Rillettes de Poulet Rôti en Cocotte (+ 10 % Gratuit)', 'fr:rillettes-francaises'),
        ('Rillettes de Poulet Rôti en Cocotte (+ 10 % Gratuit)', 'fr:rillettes-de-la-sarthe'),
        ('Rillettes de Poulet Rôti en Cocotte (+ 10 % Gratuit)', 'fr:rillettes-de-poulet-roti'),
        ('Rillettes de Poulet Rôti en Cocotte (+ 10 % Gratuit)', 'fr:rillettes-speciales'),
        ('Rillettes de canard au foie de canard', 'fr:rillettes-de-volaille'),
        ('Rillettes pur canard', 'fr:rillettes-de-volaille'),
        ('Rillettes de poulet bio', 'fr:rillettes-de-volaille'),
        ('Rillettes de poulet bio', 'fr:rillettes-francaises'),
        ('Rillettes de poulet bio', 'fr:rillettes-de-poulet-roti'),
        ('Rillettes de poulet bio', 'fr:rillettes-speciales'),
        ('Rillettes de canard', 'fr:rillettes-de-volaille'),
        ("Rillettes d'oie", 'fr:rillettes-de-volaille'),
        ("Rillettes d'oie", 'fr:rillettes-francaises'),
        ("Rillettes d'oie", 'fr:rillettes-d-oie'),
        ("Rillettes d'oie", 'fr:rillettes-speciales'),
        ('Rillettes de poulet', 'fr:rillettes-de-volaille'),
        ('Rillettes de poulet fermier aux cepes et huile d argan', 'fr:rillettes-de-volaille'),
        ("Rillettes de poulet fermer aux cepes et huile d'argan", 'fr:rillettes-de-volaille'),
        ('Rillettes de Poulet Rôti', 'fr:rillettes-de-volaille'),
        ('Rillettes de poulet rôti sans additif', 'fr:rillettes-de-volaille'),
        ('Rillettes de poulet rôti', 'fr:rillettes-de-volaille'),
        ('Chesnel Rillettes de poulet rôti 400gr', 'fr:rillettes-de-volaille'),
        ('Aiguillettes plt cert blanc', 'fr:aiguillettes-de-poulet'),
        ('Aiguillettes plt cert jaune', 'fr:aiguillettes-de-poulet'),
        ('Aiguillettes de poulet rôti au four', 'fr:aiguillettes-de-poulet'),
        ('Fines aiguillettes de Poulet Grillé', 'fr:aiguillettes-de-poulet'),
        ('Aiguillettes de poulet grillé', 'fr:aiguillettes-de-poulet'),
        ('Aiguilettes de poulet', 'fr:aiguillettes-de-poulet'),
        ('Nuggets poulet', 'fr:poulets-panes'),
        ('Nuggets au poulet croustillants bio', 'fr:poulets-panes'),
        ('Nuggets de Poulet', 'fr:poulets-panes'),
        ('Nuggets de poulet', 'fr:poulets-panes'),
        ('Panés de poulet x2', 'fr:cordons-bleus'),
        ('Panés de poulet x2', 'fr:cordons-bleus-de-poulet'),
        ('20 nuggets poulet U', 'fr:poulets-panes'),
        ("Crousty Chicken l'original", 'fr:poulets-panes'),
        ('Panés façon Milanaise Finement Citronné x2', 'fr:poulets-panes'),
        ('10 nuggets de poulet sauces curry & aigre-douce', 'fr:poulets-panes'),
        ('Crousti Nuggets de Poulet (10 environ)', 'fr:poulets-panes'),
        ('Chicken Wings Panés Créole', 'fr:poulets-panes'),
        ('Ailes de poulet pané', 'fr:poulets-panes'),
        ('Les Pana s du Volailler Nuggets de Poulet Le Gaulois 300', 'fr:poulets-panes'),
        ('Spicy de Poulet', 'fr:filet-de-poulet-halal'),
        ('Mini Chicken Schnitzels', 'fr:poulets-panes'),
        ('Allumettes fumées- 25% de sel - 2 x75g', 'fr:charcuteries-diverses'),
        ('Allumettes fumées- 25% de sel - 2 x75g', 'fr:allumettes-de-porc'),
        ('Lardons nature', 'fr:charcuteries-diverses'),
        ('Lardons nature', 'fr:allumettes-de-porc'),
        ('Lardons miel romarin', 'fr:charcuteries-diverses'),
        ('Lardons miel romarin', 'fr:allumettes-de-porc'),
        ('Allumettes de lardons', 'fr:charcuteries-diverses'),
        ('Allumettes de lardons', 'fr:allumettes-de-porc'),
        ('Lardons Nature', 'fr:charcuteries-diverses'),
        ('Lardons Nature', 'fr:allumettes-de-porc'),
        ('Lardons fumes qualité supérieure', 'fr:charcuteries-diverses'),
        ('Lardons fumes qualité supérieure', 'fr:allumettes-de-porc'),
        ('Lardons nature Auchan label rouge', 'fr:charcuteries-diverses'),
        ('Lardons nature Auchan label rouge', 'fr:allumettes-de-porc'),
        ('Lardons Qualité Supérieure Fumés', 'fr:charcuteries-diverses'),
        ('Lardons Qualité Supérieure Fumés', 'fr:allumettes-de-porc'),
        ('Lardons\nFumés', 'fr:charcuteries-diverses'),
        ('Lardons\nFumés', 'fr:allumettes-de-porc'),
        ('Allumettes de bacon fumé', 'fr:charcuteries-diverses'),
        ('Allumettes de bacon fumé', 'fr:charcuteries-a-cuire'),
        ('Allumettes\nFumées', 'fr:charcuteries-diverses'),
        ('Allumettes\nFumées', 'fr:allumettes-de-porc'),
        ('Lardons \nNature', 'fr:charcuteries-diverses'),
        ('Lardons \nNature', 'fr:allumettes-de-porc'),
        ('Lardons', 'fr:charcuteries-diverses'),
        ('Lardons', 'fr:allumettes-de-porc'),
        ('Lardons fumés, 25% de sel en moins qualité supérieure', 'fr:charcuteries-diverses'),
        ('Lardons fumés, 25% de sel en moins qualité supérieure', 'fr:allumettes-de-porc'),
        ('Lardons fumés, 25% de sel en moins qualité supérieure', 'fr:charcuteries-a-cuire'),
        ('Lardons fumés, 25% de sel en moins qualité supérieure', 'fr:meta-categorie'),
        ('Lardons nature sans couenne, sans cartilage', 'fr:charcuteries-diverses'),
        ('Lardons nature sans couenne, sans cartilage', 'fr:allumettes-de-porc'),
        ('Allumettes de lardons fumées', 'fr:charcuteries-diverses'),
        ('Allumettes de lardons fumées', 'fr:allumettes-de-porc'),
        ('Lardons fumés -25% de sel* \n*Par rapport à la moyenne des lardons du marché.', 'fr:charcuteries-diverses'),
        ('Lardons fumés -25% de sel* \n*Par rapport à la moyenne des lardons du marché.', 'fr:allumettes-de-porc'),
        ('Lardons fumés -25% de sel* \n*Par rapport à la moyenne des lardons du marché.', 'fr:charcuteries-a-cuire'),
        ('Lardons fumés -25% de sel* \n*Par rapport à la moyenne des lardons du marché.', 'fr:meta-categorie'),
        ('Lardons \nFumés', 'fr:charcuteries-diverses'),
        ('Lardons \nFumés', 'fr:allumettes-de-porc'),
        ('Lardons fumés', 'fr:charcuteries-diverses'),
        ('Lardons fumés', 'fr:allumettes-de-porc'),
        ('Bloc de foie gras de canard du Sud-Ouest', 'fr:bloc-de-foie-gras'),
        ('Bloc de foie gras de canard du Sud-Ouest', 'fr:foies-gras-mi-cuits'),
        ('Bloc de foie gras de canard', 'fr:bloc-de-foie-gras'),
        ('Bloc de Foie Gras de canard avec Morceaux', 'fr:bloc-de-foie-gras'),
        ('Bloc de Foie Gras de canard avec Morceaux', 'fr:bloc-de-foie-gras-avec-morceaux'),
        ('Bloc de Foie Gras de canard avec Morceaux', 'fr:foies-gras-mi-cuits'),
        ('Bloc de Foie Gras', 'fr:bloc-de-foie-gras'),
        ('Bloc de foie gras de canard du sud ouest', 'fr:bloc-de-foie-gras'),
        ('Bloc de foie gras de canard du Sud-Ouest avec morceaux', 'fr:bloc-de-foie-gras'),
        ('Bloc de foie gras de canard du Sud-Ouest avec morceaux', 'fr:bloc-de-foie-gras-avec-morceaux'),
        ('Bloc de foie gras de canard du Sud-Ouest avec morceaux', 'fr:foies-gras-mi-cuits'),
        ('Bloc De Foie Gras De Canard 2 Tranches Individuelles 2x40g', 'fr:bloc-de-foie-gras'),
        ('Bloc De Foie Gras De Canard 2 Tranches Individuelles 2x40g', 'fr:bloc-de-foie-gras-de-canard'),
        ('Bloc de foie gras de canard du Périgord', 'fr:bloc-de-foie-gras'),
        ('Bloc de foie gras Grande Selection Sauternes', 'fr:bloc-de-foie-gras'),
        ('Bloc foie gras canard', 'fr:bloc-de-foie-gras'),
        ('Bloc de foie gras canard avec morceaux', 'fr:bloc-de-foie-gras'),
        ('Bloc de foie gras canard avec morceaux', 'fr:bloc-de-foie-gras-avec-morceaux'),
        ('Bloc de foie gras canard avec morceaux', 'fr:foies-gras-mi-cuits'),
        ("Bloc de foie gras d'oie au Jurançon", 'fr:bloc-de-foie-gras'),
        ("Bloc de fois gras d'oie", 'fr:bloc-de-foie-gras'),
        ("Bloc de fois gras d'oie", 'fr:bloc-de-foie-gras-avec-morceaux'),
        ('Bloc Fg Canard 30%% 200g', 'fr:bloc-de-foie-gras'),
        ('Bloc Fg Canard 30%% 200g', 'fr:bloc-de-foie-gras-avec-morceaux'),
        ('Boudin blanc forestier', 'fr:boudins'),
        ('Boudin blanc forestier', 'fr:boudins-blanc-a-l-ancienne'),
        ('Boudin blanc forestier', 'fr:boudins-blancs'),
        ('Boudin blanc forestier', 'fr:entrees-chaudes'),
        ('Boudins blanc aux cèpes', 'fr:boudins'),
        ('Boudins blanc aux cèpes', 'fr:boudins-blancs'),
        ('Boudin blanc aux cepes', 'fr:boudins'),
        ('Boudin blanc aux cepes', 'fr:boudins-blancs'),
        ('Boudin Blanc au Porto', 'fr:boudins'),
        ('Boudin Blanc au Porto', 'fr:boudins-blancs'),
        ('Boudin Blanc au Porto', 'fr:boudins-blancs-au-porto'),
        ('Boudin Blanc au Porto', 'fr:entrees-chaudes'),
        ('Boudin blanc Nature au lait frais', 'fr:boudins'),
        ('Boudin blanc Nature au lait frais', 'fr:boudins-blancs'),
        ('Boudin blanc', 'fr:boudins'),
        ('Boudin blanc', 'fr:boudins-blancs'),
        ('Boudin blanc', 'fr:boudins-blancs-de-rethel'),
        ('Petits boudins blancs au foie de canard', 'fr:boudins'),
        ('Petits boudins blancs au foie de canard', 'fr:boudins-blancs'),
        ('3 Boudin blanc', 'fr:boudins'),
        ('3 Boudin blanc', 'fr:boudins-blancs'),
        ('3 Boudin blanc', 'fr:boudins-blancs-de-rethel'),
        ('Boudins blancs', 'fr:boudins'),
        ('Boudins blancs', 'fr:boudins-blancs'),
        ('Boudins blancs', 'fr:boudins-blancs-de-rethel'),
        ('Boudins blancs nature 3', 'fr:boudins'),
        ('Boudins blancs nature 3', 'fr:boudins-blancs'),
        ('La Vie Claire', 'fr:purees-de-pruneaux'),
        ('Boudins blancs à la volaille', 'fr:boudins'),
        ('Boudins blancs à la volaille', 'fr:boudins-blancs'),
        ('Boudins blancs à la truffe de la saint jean 3%', 'fr:boudins'),
        ('Boudins blancs à la truffe de la saint jean 3%', 'fr:boudins-blancs'),
        ('3 boudins blancs de volaille à la truffe', 'fr:boudins'),
        ('3 boudins blancs de volaille à la truffe', 'fr:boudins-blancs'),
        ('Boudin blanc à la truffe', 'fr:boudins'),
        ('Boudin blanc à la truffe', 'fr:boudins-blancs'),
        ('Boudin blanc thirier x 4', 'fr:boudins'),
        ('Boudin blanc thirier x 4', 'fr:boudins-blancs'),
        ('Les minis boudins blanc', 'fr:boudins'),
        ('Les minis boudins blanc', 'fr:boudins-blancs'),
        ('Boudin blanc de porc aux cepes', 'fr:boudins'),
        ('Boudin blanc de porc aux cepes', 'fr:boudins-blancs'),
        ('Boudin blanc de porc aux cepes', 'fr:boudins-blancs-aux-cepes'),
        ('Boudin blanc de porc aux cepes', 'fr:entrees-chaudes'),
        ('Feta AOP (19% MG) - 200 g - Hotos', 'fr:produits-aoc'),
        ('Feta AOP (19% MG) - 200 g - Hotos', 'fr:produits-labellises'),
        ('Comte bloc 34%mg', 'fr:comte'),
        ('Comte bloc 34%mg', 'fr:produits-aoc'),
        ('Comte bloc 34%mg', 'fr:produits-labellises'),
        ('Comté', 'fr:comte'),
        ('Comté', 'fr:produits-aoc'),
        ('Comté', 'fr:produits-labellises'),
        ('Mozzarella di Bufala Campana AOP - 150 g - Fior di Napoli', 'fr:mozzarella-di-bufala-campana'),
        ('Mozzarella di Bufala Campana AOP - 150 g - Fior di Napoli', 'fr:produits-aoc'),
        ('Mozzarella di Bufala Campana AOP - 150 g - Fior di Napoli', 'fr:produits-labellises'),
        ('Saint Marcellin IGP (21,5% MG) 240 g', 'fr:saint-marcellin'),
        ('Saint Marcellin IGP (21,5% MG) 240 g', 'fr:produits-labellises'),
        ('Quart Maroilles', 'fr:maroilles'),
        ('10 Oeufs de plein air calibre mixte', 'fr:oeufs-biologiques'),
        ('10 Oeufs de plein air calibre mixte', 'fr:oeufs-labellises'),
        ('10 Oeufs de plein air calibre mixte', 'fr:produits-labellises'),
        ('Comté AOP 15 Mois', 'fr:comte'),
        ('Comté AOP 15 Mois', 'fr:produits-aoc'),
        ('Comté AOP 15 Mois', 'fr:produits-labellises'),
        ('10 Gros œufs Plein Air Bio', 'fr:oeufs-biologiques'),
        ('10 Gros œufs Plein Air Bio', 'fr:oeufs-labellises'),
        ('10 Gros œufs Plein Air Bio', 'fr:produits-labellises'),
        ("Pâtes aux oeufs Späetzle IGP d'Alsace", 'fr:pates-d-alsace'),
        ("Pâtes aux oeufs Späetzle IGP d'Alsace", 'fr:produits-labellises'),
        ("Pâtes aux oeufs Späetzle IGP d'Alsace", 'fr:spaetzle'),
        ("Pâtes aux oeufs Späetzle IGP d'Alsace", 'fr:spatzles-d-alsace'),
        ("Pâtes d'Alsace Spaetzle (7 Œufs Frais par kilo de semoule)", 'fr:pates-d-alsace'),
        ("Pâtes d'Alsace Spaetzle (7 Œufs Frais par kilo de semoule)", 'fr:produits-labellises'),
        ("Pâtes d'Alsace Spaetzle (7 Œufs Frais par kilo de semoule)", 'fr:spaetzle'),
        ("Pâtes d'Alsace Spaetzle (7 Œufs Frais par kilo de semoule)", 'fr:spatzles-d-alsace'),
        ('Comté râpé au lait cru (32% MG)', 'fr:comte'),
        ('Comté râpé au lait cru (32% MG)', 'fr:produits-aoc'),
        ('Comté râpé au lait cru (32% MG)', 'fr:produits-labellises'),
        ("Pâtes aux œufs frais, Spaghetti (Pâtes d'Alsace)", 'fr:coquillettes'),
        ("Pâtes aux œufs frais, Spaghetti (Pâtes d'Alsace)", 'fr:pates-d-alsace'),
        ("Pâtes aux œufs frais, Spaghetti (Pâtes d'Alsace)", 'fr:coquillettes-aux-oeufs'),
        ("Pâtes aux œufs frais, Spaghetti (Pâtes d'Alsace)", 'fr:coquillettes-d-alsace'),
        ("Pâtes aux œufs frais, Spaghetti (Pâtes d'Alsace)", 'fr:produits-labellises'),
        ('Quenelles Bio 300g', 'fr:quenelles'),
        ('Ecochard Quenelle Nature 4X80G', 'fr:quenelles'),
        ('6 quenelles lyonnaises brochet', 'fr:quenelles'),
        ('Quenelle nature', 'fr:quenelles'),
        ('Maxi délices soufflés brochet Ecochard 2x150g', 'fr:quenelles'),
        ('Délices Soufflés Petits Légumes', 'fr:quenelles'),
        ('16 quenelles', 'fr:quenelles'),
        ('Quenelles nature', 'fr:quenelles'),
        ('4 quenelles fraîches de volaille fermière aux morilles', 'fr:quenelles'),
        ('Quenelles Nature, Nos Régions Ont Du Talent', 'fr:quenelles'),
        ('Quenelles de veau sauce financière', 'fr:quenelles'),
        ('Mini Quenelles à Poêler Nature', 'fr:quenelles'),
        ('Quenelles lyonnaises de brochet', 'fr:quenelles'),
        ('Quenelles lyonnaises nature', 'fr:quenelles'),
        ('Quenelles de Brochet Lot de 2', 'fr:quenelles'),
        ('Quenelles Nature Lot de 3', 'fr:quenelles'),
        ("Filets d'anchois à l'huile d'olive", 'fr:filets-d-anchois-marines'),
        ("Filets d'anchois à l'huile d'olive", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ('Filets Anchois Huile Olive Bio 48G Bocal Verre', 'fr:filets-d-anchois-marines'),
        ('Filets Anchois Huile Olive Bio 48G Bocal Verre', 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ('ANCHOIS COLLIOURE', 'fr:filets-d-anchois-marines'),
        ('ANCHOIS COLLIOURE', 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("Anchois marinés à l'huile d'olive bio", 'fr:filets-d-anchois-marines'),
        ("Anchois marinés à l'huile d'olive bio", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("Filets D'anchois à L'huile D'olive Bio", 'fr:filets-d-anchois-marines'),
        ("Filets D'anchois à L'huile D'olive Bio", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("C'est trop bon", 'fr:filets-d-anchois-marines'),
        ("C'est trop bon", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("Filets d'anchois en persillade", 'fr:filets-d-anchois-marines'),
        ("Filets d'anchois en persillade", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ('Anchois marinés au citron', 'fr:filets-d-anchois-marines'),
        ('Anchois marinés au citron', 'fr:filets-d-anchois-marines-au-citron-confit'),
        ("Filets d'anchois à l'huile de tournesol", 'fr:filets-d-anchois-marines'),
        ("Filets d'anchois à l'huile de tournesol", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("Filets d'anchois à l'huile de tournesol", 'fr:filets-d-anchois-aux-capres'),
        ('Anchois Filet Marine Olive', 'fr:filets-d-anchois-marines'),
        ('Anchois Filet Marine Olive', 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("Anchois à l'huile d'olive", 'fr:anchois-a-l-huile'),
        ('100G Pot Verre Anchois Huile Olive Grand Jury', 'fr:filets-d-anchois-marines'),
        ('100G Pot Verre Anchois Huile Olive Grand Jury', 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("Filet d'anchois à la purée d'ail", 'fr:filets-d-anchois-marines'),
        ("Filet d'anchois à la purée d'ail", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("Filets anchois à l'huile d'olive GDJ", 'fr:filets-d-anchois-marines'),
        ("Filets anchois à l'huile d'olive GDJ", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ("Filets d'anchois a l'huile d'olive", 'fr:filets-d-anchois-marines'),
        ("Filets d'anchois a l'huile d'olive", 'fr:filets-d-anchois-marines-a-l-huile-vegetale'),
        ('Morbier AOP', 'fr:morbiers'),
        ('Morbier AOP au lait cru', 'fr:morbiers'),
        ('Moelleux morbier', 'fr:morbiers'),
        ('Morbier Bio', 'fr:morbiers'),
        ('Apéro Snack-Salade Morbier', 'fr:morbiers'),
        ('Morbier', 'fr:morbiers'),
        ('Morbier Bio JuraFlore', 'fr:morbiers'),
        ('Morbier bio', 'fr:morbiers'),
        ('Le fromage blanc', 'fr:fromages-blancs'),
        ('Fromage blanc battu', 'fr:fromages-blancs'),
        ('Fromage blanc battu', 'fr:fromages-blancs-au-lait-de-vache'),
        ('Fromage blanc battu', 'fr:fromages-blancs-natures'),
        ('Fromage blanc nature', 'fr:fromages-blancs'),
        ('Fromage blanc nature', 'fr:fromages-blancs-natures'),
        ('Fromage blanc 3%mg bio', 'fr:fromages-blancs'),
        ('Fromage blanc 3%mg bio', 'fr:fromages-blancs-natures'),
        ('Fromage blanc campagne', 'fr:faisselles'),
        ('Fromage blanc campagne', 'fr:fromages-blancs'),
        ('Fromage blanc campagne', 'fr:fromages-blancs-natures'),
        ('4X125G Creme Dessert Chocolat Elle & Vire', 'fr:cremes-dessert-chocolat'),
        ('Creme dessert chocolat', 'fr:cremes-dessert-chocolat'),
        ('Crème dessert au chocolat', 'fr:cremes-dessert-chocolat'),
        ('Crème chocolat(Mont Blanc)', 'fr:cremes-dessert-chocolat'),
        ('Crème chocolat(Mont Blanc)', 'fr:cremes-desser'),
        ('Crème chocolat(Mont Blanc)', 'fr:cremes-dessert-creme-au-chocolat'),
        ('Crème chocolat(Mont Blanc)', 'fr:desserts-au-chocola'),
        ('Crème chocolat(Mont Blanc)', 'fr:desserts-lactes-au-chocola'),
        ('Danette chocolat', 'fr:cremes-dessert-chocolat'),
        ('Crème dessert saveur chocolat', 'fr:cremes-dessert-chocolat'),
        ('Delicias fondant de chocolate m.g. sin gluten', 'fr:cremes-dessert-chocolat'),
        ('Crème dessert chocolat', 'fr:cremes-dessert-chocolat'),
        ('Printiligne Crème Dessert au Chocolat', 'fr:cremes-dessert-chocolat'),
        ('Paturette Chocolat Blanc', 'fr:cremes-dessert-chocolat'),
        ('Paturette Chocolat Noir', 'fr:cremes-dessert-chocolat'),
        ('Paturette Chocolat Noir', 'fr:cremes-dessert-chocolat-noir'),
        ('Paturette Chocolat', 'fr:cremes-dessert-chocolat'),
        ('Creme dessert', 'fr:cremes-dessert-chocolat'),
        ('Danette chocolat saveur noisette', 'fr:cremes-dessert-chocolat'),
        ('Creme Cacao', 'fr:barres-glacees'),
        ('Crème fraîche de Normandie (30% MG)', 'fr:cremes-fraiches'),
        ('Crème fraîche épaisse légère', 'fr:cremes-fraiches'),
        ('Crème fraîche épaisse légère', 'fr:cremes-legeres'),
        ('Crème fraîche épaisse', 'fr:cremes-fraiches'),
        ('Crème fraîche épaisse', 'fr:cremes-legeres'),
        ('Crème fraiche épaisse', 'fr:cremes-fraiches'),
        ('Crème fraiche épaisse', 'fr:cremes-legeres'),
        ('Crème Fraîche Épaisse 30%', 'fr:cremes-entieres'),
        ('Crème Fraîche Épaisse 30%', 'fr:cremes-fraiches'),
        ('Crème fraiche entière', 'fr:cremes-entieres'),
        ('Crème fraiche entière', 'fr:cremes-fraiches'),
        ('Crème fraîche épaisseEntière', 'fr:cremes-entieres'),
        ('Crème fraîche épaisseEntière', 'fr:cremes-fraiches'),
        ('Crème fraîche épaisse Entière', 'fr:cremes-entieres'),
        ('Crème fraîche épaisse Entière', 'fr:cremes-fraiches'),
        ('Crème fraîche fluide entière (30% MG)', 'fr:cremes-entieres'),
        ('Crème fraîche fluide entière (30% MG)', 'fr:cremes-fraiches'),
        ('Crème fraîche fluide entière (30% MG)', 'fr:cremes-liquides'),
        ('Crème fraîche entière épaisse (30% M.G)', 'fr:cremes-entieres'),
        ('Crème fraîche entière épaisse (30% M.G)', 'fr:cremes-fraiches'),
        ('Creme fraiche 30%mg', 'fr:cremes-entieres'),
        ('Creme fraiche 30%mg', 'fr:cremes-fraiches'),
        ('Crème fraiche épaisse entière', 'fr:cremes-entieres'),
        ('Crème fraiche épaisse entière', 'fr:cremes-fraiches'),
        ('Crème fraîche légère épaisse', 'fr:cremes-fraiches'),
        ('Crème fraîche légère épaisse', 'fr:cremes-legeres'),
        ('Crème fraîche épaisse bio 30 % Mat. Gr.', 'fr:cremes-fraiches'),
        ('Crème fraiche gastronomique', 'fr:cremes-fraiches'),
        ('Rillettes de cul noir Limousin', 'fr:rillettes-de-viande-rouge'),
        ('Rillettes de cul noir Limousin', 'fr:rillettes-de-porc'),
        ('Rillettes du Mans', 'fr:rillettes-de-viande-rouge'),
        ('Rillettes du Mans', 'fr:rillettes-de-porc'),
        ('Rillettes du Mans', 'fr:rillettes-francaises'),
        ('Rillettes du Mans', 'fr:rillettes-de-la-sarthe'),
        ('Rillettes du Mans', 'fr:rillettes-du-mans'),
        ("Rillettes de porc au piment d'Espelette et jambon de Bayonne", 'fr:rillettes-de-viande-rouge'),
        ("Rillettes de porc au piment d'Espelette et jambon de Bayonne", 'fr:rillettes-de-porc'),
        ('Rillettes du Mans sans graisse ajouté', 'fr:rillettes-de-viande-rouge'),
        ('Rillettes du Mans sans graisse ajouté', 'fr:rillettes-francaises'),
        ('Rillettes du Mans sans graisse ajouté', 'fr:rillettes-de-la-sarthe'),
        ('Rillettes du Mans sans graisse ajouté', 'fr:rillettes-de-porc'),
        ('Rillettes du Mans sans graisse ajouté', 'fr:rillettes-du-mans'),
        ('Rillettes de porc', 'fr:rillettes-de-viande-rouge'),
        ('Rillettes de porc', 'fr:rillettes-de-porc'),
        ('Rillettes de porc', 'fr:rillettes-francaises'),
        ('Rillettes de porc', 'fr:rillettes-de-la-sarthe'),
        ('Rillettes de porc', 'fr:rillettes-du-mans'),
        ("Rillette de porc au piment d'espelette et jambon de bayonne", 'fr:rillettes-de-viande-rouge'),
        ("Rillette de porc au piment d'espelette et jambon de bayonne", 'fr:rillettes-de-porc'),
        ("Rillettes de porc au piment d'espelette et jambon de Bayonne", 'fr:rillettes-de-viande-rouge'),
        ("Rillettes de porc au piment d'espelette et jambon de Bayonne", 'fr:rillettes-de-porc'),
        ('Rillettes de Porc au Madiran et Oignons rouges confits', 'fr:rillettes-de-viande-rouge'),
        ('Rillettes de Porc au Madiran et Oignons rouges confits', 'fr:rillettes-de-porc'),
        ('Rillette pur porc', 'fr:rillettes-de-viande-rouge'),
        ('Rillette pur porc', 'fr:rillettes-de-porc'),
        ('Rillette pur porc', 'fr:rillettes-francaises'),
        ('Rillette pur porc', 'fr:rillettes-de-la-sarthe'),
        ('Rillette pur porc', 'fr:rillettes-du-mans'),
        ('Rillettes Du Mans Tradilège,', 'fr:rillettes-de-viande-rouge'),
        ('Rillettes Du Mans Tradilège,', 'fr:rillettes-de-porc'),
        ('Rillettes Du Mans Tradilège,', 'fr:rillettes-francaises'),
        ('Rillettes Du Mans Tradilège,', 'fr:rillettes-de-la-sarthe'),
        ('Rillettes Du Mans Tradilège,', 'fr:rillettes-du-mans'),
        ('Cordon bleu au poulet 1kg', 'fr:cordons-bleus'),
        ('Cordon bleu au poulet 1kg', 'fr:cordons-bleus-de-poulet'),
        ('Cordon bleu de dinde x2', 'fr:cordons-bleus'),
        ('Cordon bleu de dinde x2', 'fr:cordons-bleus-de-poulet'),
        ("Les Maxis Croq' dés de jambon de dinde et fromage", 'fr:cordons-bleus'),
        ("Les Maxis Croq' dés de jambon de dinde et fromage", 'fr:cordons-bleus-de-dinde'),
        ('Cordon bleu x 2', 'fr:cordons-bleus'),
        ('Cordon bleu x 2', 'fr:cordons-bleus-de-poulet'),
        ('Escalope Cordon Bleu de Poulet (x 1)', 'fr:cordons-bleus'),
        ('Escalope Cordon Bleu de Poulet (x 1)', 'fr:cordons-bleus-de-poulet'),
        ('Cordons Bleu Fromage', 'fr:cordons-bleus'),
        ('Cordons Bleu Fromage', 'fr:cordons-bleus-de-dinde'),
        ('Cordons bleus', 'fr:cordons-bleus'),
        ('Cordons bleus', 'fr:cordons-bleus-de-poulet'),
        ('Cordon bleu de poulet', 'fr:cordons-bleus'),
        ('Cordon bleu de poulet', 'fr:cordons-bleus-de-poulet'),
        ('Cordon Bleu au Comté fondu (x 2)', 'fr:cordons-bleus'),
        ('Cordon Bleu au Comté fondu (x 2)', 'fr:cordons-bleus-de-poulet'),
        ("L'escalope Cordon Bleu", 'fr:cordons-bleus'),
        ("L'escalope Cordon Bleu", 'fr:cordons-bleus-de-poulet'),
        ('Cordon Bleu de Dinde', 'fr:cordons-bleus'),
        ('Cordon Bleu de Dinde', 'fr:cordons-bleus-de-poulet'),
        ('2 cordons bleus de volaille', 'fr:cordons-bleus'),
        ('2 cordons bleus de volaille', 'fr:cordons-bleus-de-poulet'),
        ('Cordon bleu de Dinde', 'fr:cordons-bleus'),
        ('Cordon bleu de Dinde', 'fr:cordons-bleus-de-poulet'),
        ("L'escalope Cordon Bleu de Poulet x2", 'fr:cordons-bleus'),
        ("L'escalope Cordon Bleu de Poulet x2", 'fr:cordons-bleus-de-poulet'),
        ("L'escalope Cordon Bleu de dinde x4", 'fr:cordons-bleus'),
        ("L'escalope Cordon Bleu de dinde x4", 'fr:cordons-bleus-de-dinde'),
        ('Cordons bleus de dinde', 'fr:cordons-bleus'),
        ('Cordons bleus de dinde', 'fr:cordons-bleus-de-poulet'),
        ('Cordons bleus de poulet picard', 'fr:cordons-bleus'),
        ('Cordons bleus de poulet picard', 'fr:cordons-bleus-de-poulet'),
        ('Culinea Hähnchen Cordon Bleu', 'fr:cordons-bleus'),
        ('Culinea Hähnchen Cordon Bleu', 'fr:cordons-bleus-de-poulet'),
        ('Escalope de cordon bleu poulet - 25% de sel en moins', 'fr:cordons-bleus'),
        ('Escalope de cordon bleu poulet - 25% de sel en moins', 'fr:cordons-bleus-de-poulet'),
        ('Cordons Bleus de dinde (x 2)', 'fr:cordons-bleus'),
        ('Cordons Bleus de dinde (x 2)', 'fr:cordons-bleus-de-poulet'),
        ('Atún en aceite vegetal', 'fr:thons-a-l-huile'),
        ("Thon entier à l'huile de tournesol pêché canne", 'fr:thons-a-l-huile'),
        ("Thon entier à l'huile de tournesol pêché canne", 'fr:thons-a-l-huile-de-tournesol'),
        ("Thon à l'huile de tournesol", 'fr:thons-a-l-huile'),
        ("Thon à l'huile de tournesol", 'fr:thons-a-l-huile-de-tournesol'),
        ('Atún En Aceite De Girasol', 'fr:thons-a-l-huile'),
        ('Atún En Aceite De Girasol', 'fr:thons-a-l-huile-de-tournesol'),
        ('Atún girasol', 'fr:thons-a-l-huile'),
        ('Atún girasol', 'fr:thons-a-l-huile-de-tournesol'),
        ("Thon Entier à L'huile De Tournesol", 'fr:thons-a-l-huile'),
        ("Thon Entier à L'huile De Tournesol", 'fr:thons-a-l-huile-de-tournesol'),
        ("Miettes de thon à l'huile de Tournesol 160g CASINO", 'fr:thons-a-l-huile'),
        ("Miettes de thon à l'huile de Tournesol 160g CASINO", 'fr:thons-a-l-huile-de-tournesol'),
        ('Atun En Aciete Vegetal Salvora', 'fr:thons-a-l-huile'),
        ('Atun En Aciete Vegetal Salvora', 'fr:thons-a-l-huile-de-tournesol'),
        ("Filet de thon à l'huile de tournesol", 'fr:thons-a-l-huile'),
        ("Filet de thon à l'huile de tournesol", 'fr:thons-a-l-huile-de-tournesol'),
        ('Atum posta em óleo vegetal', 'fr:thons-a-l-huile'),
        ('Atum posta em óleo vegetal', 'fr:thons-a-l-huile-de-tournesol'),
        ('Atum posta em óleo vegetal', 'fr:thon-a-l-huile-vegetale'),
        ("Miettes de thon à l'huile de tournesol", 'fr:thons-a-l-huile'),
        ("Miettes de thon à l'huile de tournesol", 'fr:thons-a-l-huile-de-tournesol'),
        ('Miettes De Thon', 'fr:miettes-de-thon-a-la-tomate'),
        ('Thon rose', 'fr:thons-blancs-au-naturel'),
        ("Thon à l'huile de Tournesol", 'fr:thons-a-l-huile'),
        ("Thon à l'huile de Tournesol", 'fr:thons-a-l-huile-de-tournesol'),
        ('Brioche tressée pépites de chocolat', 'fr:brioches-au-chocolat'),
        ('Brioche tressée pépites de chocolat', 'fr:brioches-tressees'),
        ('Brioche Tranchée', 'fr:brioches-tranchees'),
        ('Brioches chocolats', 'fr:brioches-au-chocolat'),
        ('Brioches chocolats', 'fr:brioches-tranchees'),
        ('Briochettes pépites de chocolat lait', 'fr:brioches-au-chocolat'),
        ('La gâche tranchée aux pépites de chocolat', 'fr:brioches-au-chocolat'),
        ('La gâche tranchée aux pépites de chocolat', 'fr:brioches-tranchees'),
        ('La gâche tranchée aux pépites de chocolat', 'fr:gaches'),
        ('Brioche facon moelleux au chocolat', 'fr:brioches-au-chocolat'),
        ('Pitch brioches pépites chocolat', 'fr:brioches-au-chocolat'),
        ('Brioches aux pepites de chocolat', 'fr:brioches-au-chocolat'),
        ('Brioches aux pepites de chocolat', 'fr:brioches-tranchees'),
        ('Brioches aux pepites de chocolat', 'fr:gaches'),
        ('Briochettes aux Petits Carrés de Chocolat', 'fr:brioches-au-chocolat'),
        ('Pitch Choco Barre - Chocolat au Lait', 'fr:brioches-au-chocolat'),
        ('Petits Chinois (x 6) aux pépites de chocolat - 300 g - La Fournée Dorée', 'fr:brioches-au-chocolat'),
        ('Petits Chinois (x 6) aux pépites de chocolat - 300 g - La Fournée Dorée', 'fr:chinois'),
        ('Petits Chinois (x 6) aux pépites de chocolat - 300 g - La Fournée Dorée', 'fr:mini-chinois-au-chocolat'),
        ('Gâche tranchée aux pépites de chocolat', 'fr:brioches-au-chocolat'),
        ('Gâche tranchée aux pépites de chocolat', 'fr:brioches-tranchees'),
        ('Gâche tranchée aux pépites de chocolat', 'fr:gaches'),
        ('Brioche trenzado con pepitas de chocolate', 'fr:brioches-au-chocolat'),
        ('9 Mini chocolate hot cross buns', 'fr:brioches-au-chocolat'),
        ('8 briochettes pépites chocolat', 'fr:brioches-au-chocolat'),
        ('Brioche Nanterre aux pepites de chocolat', 'fr:brioches-au-chocolat'),
        ('Brioche tressée aux pépites de chocolat', 'fr:brioches-au-chocolat'),
        ('Brioche tressée aux pépites de chocolat', 'fr:brioches-tranchees'),
        ('Brioche tressée aux pépites de chocolat', 'fr:brioches-tressees'),
        ('Brioche tressée aux pépites de chocolat', 'fr:brioches-tranchees-au-chocolat'),
        ('Brioche tressée aux pépites de chocolat', 'fr:brioches-tressees-au-chocolat'),
        ('Brioche tressée aux pépites de chocolat', 'fr:brioches-tressees-au-levain'),
        ('Brioche tressée aux pépites de chocolat', 'fr:brioches-tressees-au-levain-et-au-chocolat'),
        ('Brioche tressée aux pépites de chocolat et perles de sucre', 'fr:brioches-au-chocolat'),
        ('Brioche tressée aux pépites de chocolat et perles de sucre', 'fr:brioches-tressees'),
        ('Briochettes pepites de chocolat lait', 'fr:brioches-au-chocolat'),
        ('12 Crêpes de Landerneau', 'fr:crepes-de-froment'),
        ('Crêpes au Froment', 'fr:crepes-de-froment'),
        ('Crêpes bretonnes', 'fr:crepes-de-froment'),
        ('Crêpes de Bretagne au froment', 'fr:crepes-de-froment'),
        ('Crêpes de Froment', 'fr:crepes-de-froment'),
        ('Crêpes de froment', 'fr:crepes-de-froment'),
        ('6 petites crêpes de froment', 'fr:crepes-de-froment'),
        ('20 Crêpes  fraîches Au Froment Sucrées', 'fr:crepes-de-froment'),
        ('Crêpes TY DÉLICE', 'fr:crepes-de-froment'),
        ('6 crêpes fraiches de froment', 'fr:crepes-de-froment'),
        ('12 crepes de froment', 'fr:crepes-de-froment'),
        ('12 Crêpes Traditionnelles au Lait Frais - Pur Beurre', 'fr:crepes-de-froment'),
        ('6 crêpes de froment', 'fr:crepes-de-froment'),
        ('Roquefort', 'fr:roqueforts'),
        ('Roquefort aop', 'fr:roqueforts'),
        ('Roquefort bio A.O.P. 32% Mat. Gr.', 'fr:roqueforts'),
        ('GorgonzolaAldi', 'fr:roqueforts'),
        ('Roquefort (32 % MG)', 'fr:roqueforts'),
        ('Roquefort (32 % MG)', 'fr:produits-aoc'),
        ('Roquefort (32 % MG)', 'fr:produits-labellises'),
        ('Roquefort AOP Bio', 'fr:roqueforts'),
        ('Roquefort Gabriel coulet', 'fr:roqueforts'),
        ('Roquefort Gabriel Coulet 150 g', 'fr:roqueforts'),
        ('Roquefort Aop Portion', 'fr:roqueforts'),
        ('Roquefort AOP', 'fr:roqueforts'),
        ('Societe Tranches Roquefort', 'fr:roqueforts'),
        ('Roquefort AOP 32% Mat. Gr.', 'fr:roqueforts'),
        ('Roquefort (31,7% MG)', 'fr:roqueforts'),
        ('Roquefort Papillon Rouge', 'fr:roqueforts'),
        ('Tyrolia vanille et fruits rouges', 'fr:buches-glacees'),
        ('Bûche façon Dame Blanche', 'fr:buches-glacees'),
        ('Buche glacée artisanale Mascarpone - Myrtille', 'fr:buches-glacees'),
        ('Buche glacée facon rocher', 'fr:buches-glacees'),
        ('Buche glacée création chocolat praliné', 'fr:buches-glacees'),
        ('Bûche glacée fruits exotiques', 'fr:buches-glacees'),
        ('Création figue, miel, noix', 'fr:buches-glacees'),
        ('Bûche glacée 3 chocolat', 'fr:buches-glacees'),
        ('Buche glacée vanille noisette', 'fr:buches-de-noel'),
        ('Buche glacée vanille noisette', 'fr:buches-glacees'),
        ('Bûche glacée nougat caramel', 'fr:buches-glacees'),
        ('Buche glacee. Fruits rouges et framvoise', 'fr:buches-glacees'),
        ('Bûche glacée fraise pistache', 'fr:buches-glacees'),
        ('Bûche glacée crème brûlée', 'fr:buches-glacees'),
        ("Rêve d'Hiver", 'fr:buches-glacees'),
        ('Buche glacée fruits du verger', 'fr:buches-glacees'),
        ('Bûche glacée\nChocolats noisettes caramélisées', 'fr:buches-glacees'),
        ('Bûche glacée\nExotique\nVanille, Mangue & passion', 'fr:buches-glacees'),
        ('Bûche glacée\nVanille Fruits Rouges', 'fr:buches-glacees'),
        ("3D's Bugles, Goût Fromage", 'fr:biscuits-aperitifs-souffles'),
        ("3D's Bugles, Goût Fromage", 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Croustillants à la Cacahuète', 'fr:biscuits-aperitifs-souffles'),
        ('Croustillants à la Cacahuète', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Croustillants à la Cacahuète', 'fr:biscuits-aperitif-souffles-a-la-cacahuete'),
        ('Curly donuts cacahuète caramélisée sucrée-salée', 'fr:biscuits-aperitifs-souffles'),
        ('Curly donuts cacahuète caramélisée sucrée-salée', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Curly donuts cacahuète caramélisée sucrée-salée', 'fr:biscuits-aperitif-souffles-a-la-cacahuete'),
        ('Craquilles au Fromage', 'fr:biscuits-aperitifs-souffles'),
        ('Craquilles au Fromage', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Craquilles au Fromage', 'fr:biscuits-aperitif-souffles-au-fromage'),
        ('Cheese Flips', 'fr:biscuits-aperitifs-souffles'),
        ('Cheese Flips', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Minions stick de maïs salés', 'fr:biscuits-aperitifs-souffles'),
        ('Minions stick de maïs salés', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Cuquitos sabor Queso', 'fr:biscuits-aperitifs-souffles'),
        ('Cuquitos sabor Queso', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Curly Donuts', 'fr:biscuits-aperitifs-souffles'),
        ('Curly Donuts', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Curly Donuts', 'fr:biscuits-aperitif-souffles-a-la-cacahuete'),
        ("Dugadoo's", 'fr:biscuits-aperitifs-souffles'),
        ("Dugadoo's", 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Maïs soufflés minis fromage', 'fr:biscuits-aperitifs-fourres-au-fromage'),
        ('Maïs soufflés minis fromage', 'fr:biscuits-aperitifs-souffles'),
        ('Maïs soufflés minis fromage', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Maïs soufflés minis fromage', 'fr:crakers'),
        ("Curly cacahuète l'Original", 'fr:biscuits-aperitifs-souffles'),
        ("Curly cacahuète l'Original", 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ("Curly cacahuète l'Original", 'fr:biscuits-aperitif-souffles-a-la-cacahuete'),
        ("Grignot'goût cacahuete", 'fr:biscuits-aperitifs-souffles'),
        ("Grignot'goût cacahuete", 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ("Grignot'goût cacahuete", 'fr:biscuits-aperitif-souffles-a-la-cacahuete'),
        ('Flips Cacahuètes', 'fr:biscuits-aperitifs-souffles'),
        ('Flips Cacahuètes', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Flips Cacahuètes', 'fr:biscuits-aperitif-souffles-a-la-cacahuete'),
        ('3D bugles goût bacon', 'fr:biscuits-aperitifs-souffles'),
        ('3D bugles goût bacon', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('3D bugles goût bacon', 'fr:biscuits-aperitif-souffles-au-bacon'),
        ("3D's Bugles goût Jambon-Fromage de l'Espace", 'fr:biscuits-aperitifs-souffles'),
        ("3D's Bugles goût Jambon-Fromage de l'Espace", 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ("3D's Bugles goût Jambon-Fromage de l'Espace", 'fr:biscuits-aperitif-souffles-au-fromage'),
        ("3D's Bugles, Goût Cacahuète", 'fr:biscuits-aperitifs-souffles'),
        ("3D's Bugles, Goût Cacahuète", 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ("3D's Bugles, Goût Cacahuète", 'fr:biscuits-aperitif-souffles-a-la-cacahuete'),
        ('Producto de aperitivo de maíz horneado sabor barbacoa', 'fr:biscuits-aperitifs-souffles'),
        ('Producto de aperitivo de maíz horneado sabor barbacoa', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Croustille Belin Emmental 138g Croustille Belin Emmental', 'fr:biscuits-aperitifs-souffles'),
        ('Croustille Belin Emmental 138g Croustille Belin Emmental', 'fr:biscuits-aperitifs-souffles-a-base-de-mais'),
        ('Croustille Belin Emmental 138g Croustille Belin Emmental', 'fr:biscuits-aperitifs-au-fromage'),
        ("Pruneaux d'agen", 'fr:pruneaux-d-agen'),
        ("Pruneaux d'Agen", 'fr:pruneaux-d-agen'),
        ('Figues Lerida', 'fr:variete-lerida'),
        ('Cocktail 50GR - MANI', 'fr:aliments-a-base-de-plantes-seches'),
        ("Pruneaux D'Agen", 'fr:pruneaux-d-agen'),
        ('Amande émondée,', 'fr:aliments-a-base-de-plantes-seches'),
        ("Pruneaux d'Agen Dénoyautés", 'fr:pruneaux-d-agen'),
        ('Dattes Sidi Mehrez', 'fr:aliments-a-base-de-plantes-seches'),
        ('Dattes de Tunisie', 'fr:aliments-a-base-de-plantes-seches'),
        ('Figues sèches Layer holy', 'fr:aliments-a-base-de-plantes-seches'),
        ('Galette au Blé Noir Jambon Emmental', 'fr:galettes-de-ble-noir'),
        ('Galette au Blé Noir Jambon Emmental', 'fr:galettes-garnies'),
        ('Galette de blé noir jambon emmental mozzarella', 'fr:galettes-de-ble-noir'),
        ('Galette mozzarella tomate basilic', 'fr:galettes-preparees'),
        ('Galettes de blé noir, certifié AB', 'fr:galettes-de-ble-noir'),
        ('6 Galettes de Blé Noir Tradition Bretagne Biologiques en sachet', 'fr:galettes-de-ble-noir'),
        ('Galette de Blé Noir', 'fr:cereales-de-grains-souffles'),
        ('Galette de Blé Noir', 'fr:galettes-de-cereales-bio'),
        ('Galette de Blé Noir', 'fr:galettes-de-froment-complet'),
        ('Galette de Blé Noir', 'fr:galettes-de-sarrasin-ou-ble-noir-complet'),
        ('Galette de Blé Noir', 'fr:origine-vegetale'),
        ('Galettes fondue de poireaux et saumon', 'fr:galettes-de-ble-noir'),
        ('Galettes fondue de poireaux et saumon', 'fr:galettes-cuisines'),
        ('Galettes de blé noir x4', 'fr:galettes-de-ble-noir'),
        ('Galettes de Blé Noir', 'fr:cereales-de-grains-souffles'),
        ('Galettes de Blé Noir', 'fr:galettes-de-cereales-bio'),
        ('Galettes de Blé Noir', 'fr:galettes-de-froment-complet'),
        ('Galettes de Blé Noir', 'fr:galettes-de-sarrasin-ou-ble-noir-complet'),
        ('Galettes de Blé Noir', 'fr:origine-vegetale'),
        ('Galettes de blé noir bio', 'fr:cereales-de-grains-souffles'),
        ('Galettes de blé noir bio', 'fr:galettes-de-cereales-bio'),
        ('Galettes de blé noir bio', 'fr:galettes-de-froment-complet'),
        ('Galettes de blé noir bio', 'fr:galettes-de-sarrasin-ou-ble-noir-complet'),
        ('Galettes de blé noir bio', 'fr:origine-vegetale'),
        ('Galettes Blé Noir', 'fr:cereales-de-grains-souffles'),
        ('Galettes Blé Noir', 'fr:galettes-de-cereales-bio'),
        ('Galettes Blé Noir', 'fr:galettes-de-froment-complet'),
        ('Galettes Blé Noir', 'fr:galettes-de-sarrasin-ou-ble-noir-complet'),
        ('Galettes Blé Noir', 'fr:origine-vegetale'),
        ('4 galettes de blé noir BIO', 'fr:cereales-de-grains-souffles'),
        ('4 galettes de blé noir BIO', 'fr:galettes-de-cereales-bio'),
        ('4 galettes de blé noir BIO', 'fr:galettes-de-froment-complet'),
        ('4 galettes de blé noir BIO', 'fr:galettes-de-sarrasin-ou-ble-noir-complet'),
        ('4 galettes de blé noir BIO', 'fr:origine-vegetale'),
        ('6 Galettes 100% Blé Noir', 'fr:galettes-de-ble-noir'),
        ('Galettes blé noir', 'fr:cereales-de-grains-souffles'),
        ('Galettes blé noir', 'fr:galettes-de-cereales-bio'),
        ('Galettes blé noir', 'fr:galettes-de-froment-complet'),
        ('Galettes blé noir', 'fr:galettes-de-sarrasin-ou-ble-noir-complet'),
        ('Galettes blé noir', 'fr:origine-vegetale'),
        ('Galettes jambon, champignons & emmental', 'fr:galettes-de-ble-noir'),
        ('Galettes jambon, champignons & emmental', 'fr:galettes-garnies'),
        ('Galette de blé noir Jambon, emmental', 'fr:galettes-de-ble-noir'),
        ('Galette de blé noir Jambon, emmental', 'fr:galettes-garnies'),
        ('6 galettes farine de blé noir de bretagne IGP', 'fr:galettes-de-ble-noir'),
        ('Galette de Bretagne - Champignons & Lardons rissolés', 'fr:galettes-de-ble-noir'),
        ('Galette de Bretagne - Chiffonnade de Jambon & Emmental', 'fr:galettes-de-ble-noir'),
        ('Riz basmati nature', 'fr:cereales-preparees'),
        ('Riz basmati nature', 'fr:riz-prepares'),
        ('Riz cantonais', 'fr:cereales-preparees'),
        ('Riz cantonais', 'fr:riz-prepares'),
        ('Special Mushroom Rice', 'fr:cereales-preparees'),
        ('Special Mushroom Rice', 'fr:riz-prepares'),
        ('Riz & Lentilles au Curry', 'fr:cereales-preparees'),
        ('Riz & Lentilles au Curry', 'fr:riz-prepares'),
        ('Riz Cantonais', 'fr:cereales-preparees'),
        ('Riz Cantonais', 'fr:riz-prepares'),
        ('Express Langkorn & Wildreis', 'fr:cereales-preparees'),
        ('Express Langkorn & Wildreis', 'fr:riz-prepares'),
        ('Special Tomato And Basil Rice', 'fr:cereales-preparees'),
        ('Special Tomato And Basil Rice', 'fr:riz-prepares'),
        ('Riz à la cantonaise', 'fr:cereales-preparees'),
        ('Riz à la cantonaise', 'fr:riz-prepares'),
        ('Riz Thaî au Citron Vert et aux Herbes', 'fr:cereales-preparees'),
        ('Riz Thaî au Citron Vert et aux Herbes', 'fr:riz-prepares'),
        ('Riz paëlla', 'fr:plats-a-base-de-mollusques'),
        ('Risoto mix Genovese', 'fr:cereales-preparees'),
        ('Risoto mix Genovese', 'fr:riz-prepares'),
        ('Riz cantonais Nasi Goreng', 'fr:cereales-preparees'),
        ('Riz cantonais Nasi Goreng', 'fr:riz-prepares'),
        ('Riz cantonais Nasi Goreng', 'fr:plats-prepares-a-rechauffer-au-bain-marie'),
        ('Riz cantonais Nasi Goreng', 'fr:riz-cantonais-nasi-goreng'),
        ('Riz Paëlla', 'fr:plats-a-base-de-mollusques'),
        ('Riz cuisiné citron et romarin', 'fr:cereales-preparees'),
        ('Riz cuisiné citron et romarin', 'fr:riz-prepares'),
        ('Riz basmati 2mn', 'fr:cereales-preparees'),
        ('Riz basmati 2mn', 'fr:riz-prepares'),
        ('Mimolette extra vieille', 'fr:fromages-du-nord-pas-de-calais'),
        ('Mimolette extra vieille', 'fr:mimolettes'),
        ('Mimolette extra-vielle', 'fr:fromages-du-nord-pas-de-calais'),
        ('Mimolette extra-vielle', 'fr:mimolettes'),
        ('Mimolette 23,7% Mat. Gr.', 'fr:fromages-du-nord-pas-de-calais'),
        ('Mimolette 23,7% Mat. Gr.', 'fr:mimolettes'),
        ('Mimolette vieille', 'fr:fromages-du-nord-pas-de-calais'),
        ('Mimolette vieille', 'fr:mimolettes'),
        ('Mimolette Hollandaise - 8 tranches environ', 'fr:fromages-du-nord-pas-de-calais'),
        ('Mimolette Hollandaise - 8 tranches environ', 'fr:mimolettes'),
        ('Mimolette Bio (27 % MG) Demi-vieille', 'fr:fromages-du-nord-pas-de-calais'),
        ('Mimolette Bio (27 % MG) Demi-vieille', 'fr:mimolettes'),
        ('Pavés de saumon', 'fr:paves-de-saumon'),
        ('Les milanaises', 'fr:poulets-panes'),
        ('Les Milanaises', 'fr:poulets-panes'),
        ('Les milanaises du chef au poivre', 'fr:escalopes-de-dinde-marinees-a-la-milanaise'),
        ('Les milanaises du chef au poivre', 'fr:escalopes-de-dinde-panees'),
        ('Palmiers feuilletés croustillants', 'fr:palmiers'),
        ('Les palmiers', 'fr:palmiers'),
        ('Bio palmiers', 'fr:palmiers'),
        ('Palmiers', 'fr:palmiers'),
        ('Palmiers feuilletés', 'fr:palmiers'),
        ("Le pave d'antoinette au piment d'Espelette", 'fr:saucissons'),
        ("Le pave d'antoinette au piment d'Espelette", 'fr:saucisses-seches'),
        ('Saucisse sèche', 'fr:saucissons'),
        ('Saucisse sèche', 'fr:saucisses-seches'),
        ('Saucisse sèche', 'fr:saucissons-secs'),
        ('Saucisse sèche', 'fr:saucissons-de-jambon'),
        ('Saucisse sèche pur porc', 'fr:saucissons'),
        ('Saucisse sèche pur porc', 'fr:saucisses-seches'),
        ('Mini bâtonnets Saucisses sèches', 'fr:saucissons'),
        ('Mini bâtonnets Saucisses sèches', 'fr:saucisses-seches'),
        ('Saucisse seche', 'fr:saucissons'),
        ('Saucisse seche', 'fr:saucisses-seches'),
        ('Saucisse seche', 'fr:saucissons-secs'),
        ('Saucisse seche', 'fr:saucissons-de-jambon'),
        ('Saucisse sèche 1967', 'fr:saucissons'),
        ('Saucisse sèche 1967', 'fr:saucisses-seches'),
        ('Saucisse seche traditionelle', 'fr:saucissons'),
        ('Saucisse seche traditionelle', 'fr:saucisses-seches'),
        ('Rosette aux Herbes', 'fr:saucissons'),
        ('Rosette aux Herbes', 'fr:rosettes'),
        ('Rosette (10 tranches)', 'fr:saucissons'),
        ('Rosette (10 tranches)', 'fr:rosettes'),
        ('Rosette grande tranche -25% sel', 'fr:saucissons'),
        ('Rosette grande tranche -25% sel', 'fr:rosettes'),
        ('Rosette en tranches Label Rouge', 'fr:saucissons'),
        ('Rosette en tranches Label Rouge', 'fr:rosettes'),
        ('Mini rosette', 'fr:saucissons'),
        ('Mini rosette', 'fr:rosettes'),
        ('Merguez', 'fr:merguez'),
        ('Merguez', 'fr:merguez-veritable'),
        ('Véritable Merguez Boeuf & Mouton (x 12)', 'fr:merguez'),
        ('Véritable Merguez Boeuf & Mouton (x 12)', 'fr:charcuteries-a-cuire'),
        ('6 Merguez (Bœuf - Mouton)', 'fr:merguez'),
        ('6 Merguez (Bœuf - Mouton)', 'fr:charcuteries-a-cuire'),
        ('6 Merguez Véritables', 'fr:merguez'),
        ('6 Merguez Véritables', 'fr:merguez-veritable'),
        ('Merguez bio x5', 'fr:merguez'),
        ('Véritable merguez', 'fr:merguez'),
        ('Véritable merguez', 'fr:merguez-veritable'),
        ('Veritables Merguez', 'fr:merguez'),
        ('Veritables Merguez', 'fr:merguez-veritable'),
        ('Nonnettes au miel et à la cerise', 'fr:nonnettes'),
        ('La Nonette', 'fr:nonnettes'),
        ('Nonnettes à la mirabelle', 'fr:nonnettes'),
        ('Maison Fossier - Nonnettes - Coeur Fondant Ã La Mirabelle De Lorraine', 'fr:nonnettes'),
        ('Nonnettes Bio au miel et à la Framboise', 'fr:nonnettes'),
        ('Nonnettes Bio au miel et à la Framboise', 'fr:nonnettes-a-la-framboise'),
        ("Nonnette au miel 21% et à l'abricot", 'fr:nonnettes'),
        ("Nonnette au miel 21% et à l'abricot", 'fr:nonnettes-a-l-abricot'),
        ("Nonnettes au miel et a l'orange", 'fr:nonnettes'),
        ('Nonette', 'fr:nonettes'),
        ("Nonnettes au Miel et à l'orange", 'fr:nonnettes'),
        ('Nonnettes au miel', 'fr:nonnettes'),
        ('Nonettes cassis', 'fr:nonnettes'),
        ('La nonnette myrtille', 'fr:nonnettes'),
        ('La nonnette myrtille', 'fr:nonnettes-a-la-myrtille'),
        ('6 Nonnettes au miel', 'fr:nonnettes'),
        ('La Nonnette', 'fr:nonnettes'),
        ("Nonnette à l'orange", 'fr:nonnettes'),
        ('Nonnettes de Dijon fraise et rose', 'fr:nonnettes'),
        ('Nonnettes de Dijon fraise et rose', 'fr:nonnettes-a-la-fraise'),
        ('Crème caramel aux œufs frais', 'fr:desserts-lactes-a-la-vanille'),
        ('Crème caramel aux œufs frais', 'fr:desserts-lactes-aux-oeufs'),
        ('Crème caramel aux œufs frais', 'fr:iles-flottantes'),
        ('Crème aux oeufs à la noix de coco', 'fr:desserts-lactes-aux-oeufs'),
        ('Crème aux oeufs à la noix de coco', 'fr:iles-flottantes'),
        ('Crème Caramel Cuite & Dorée au four', 'fr:desserts-lactes-aux-oeufs'),
        ('Crème Caramel Cuite & Dorée au four', 'fr:cremes-caramel'),
        ('Petit pot de crème au caramel', 'fr:cremes-dessert-caramel'),
        ('Crème aux oeufs au caramel et fleur de sel', 'fr:desserts-lactes-aux-oeufs'),
        ('Crème aux Oeufs Arôme Vanille', 'fr:desserts-lactes-a-la-vanille'),
        ('Crème aux Oeufs Arôme Vanille', 'fr:desserts-lactes-aux-oeufs'),
        ('Crème aux Oeufs Arôme Vanille', 'fr:iles-flottantes'),
        ('Le Petit Pot de Crème Saveur Biscuit', 'fr:desserts-lactes-aux-oeufs'),
        ('Desserts lactés à la crème aux oeufs frais saveur café', 'fr:desserts-lactes-aux-oeufs'),
        ('Petit Pot de Crème Au Chocolat', 'fr:cremes-dessert-chocolat'),
        ('Petit Pot de Crème Au Chocolat', 'fr:cremes-dessert-chocolat-noir'),
        ('Le Petit pot de crème au Caramel', 'fr:cremes-dessert-caramel'),
        ('Crèmes aux œufs saveur vanille', 'fr:desserts-lactes-a-la-vanille'),
        ('Crèmes aux œufs saveur vanille', 'fr:desserts-lactes-aux-oeufs'),
        ('Crèmes aux œufs saveur vanille', 'fr:cremes-aux-oeufs'),
        ('Crème caramel X8', 'fr:desserts-lactes-aux-oeufs'),
        ('Crème caramel X8', 'fr:cremes-au-caramel'),
        ('Crème caramel X8', 'fr:cremes-aux-oeufs'),
        ('Crème aux Œufs Saveur Vanille', 'fr:desserts-lactes-a-la-vanille'),
        ('Crème aux Œufs Saveur Vanille', 'fr:desserts-lactes-aux-oeufs'),
        ('Crème aux Œufs Saveur Vanille', 'fr:cremes-aux-oeufs'),
        ('Crème aux oeufs au chocolat', 'fr:cremes-dessert-chocolat'),
        ('Crème aux oeufs au chocolat', 'fr:desserts-lactes-aux-oeufs'),
        ('Crème aux oeufs frais', 'fr:desserts-lactes-au-cafe'),
        ('Crème aux oeufs frais', 'fr:desserts-lactes-aux-oeufs'),
        ('Creme aux oeufs frais', 'fr:desserts-lactes-au-cafe'),
        ('Creme aux oeufs frais', 'fr:desserts-lactes-aux-oeufs'),
        ("Crème aux œufs saveur vanille sur lit à l'orange - cuite et dorée au four", 'fr:desserts-lactes-aux-oeufs'),
        ("Crème aux œufs saveur vanille sur lit à l'orange - cuite et dorée au four", 'fr:creme-aux-oeufs'),
        ('Crème caramel', 'fr:barres-glacees'),
        ('Crème aux oeufs à la noix de coco sur lit de caramel', 'fr:desserts-lactes-aux-oeufs'),
        ('Choucroute garnie', 'fr:choucroutes-garnies'),
        ('Choucroute garnie supérieure', 'fr:choucroutes-garnies'),
        ('Choucroute garnie supérieure', 'fr:choucroutes-royales'),
        ('Choucroute royale alsacienne', 'fr:choucroutes-garnies'),
        ("Véritable choucroute d'Alsace cuisinée au Riesling et à la graisse d'oie, qualité supérieure", 'fr:choucroutes-garnies'),
        ("Choucroute Royale, Au Riesling d'Alsace", 'fr:choucroutes-garnies'),
        ('1898 Choucroute Royale, Au Riesling', 'fr:choucroutes-garnies'),
        ('La choucroute garnie au vin blanc', 'fr:choucroutes-garnies'),
        ('Choucroute garnie cuisinée au Riesling pur porc', 'fr:choucroutes-garnies'),
        ("Choucroute garnie d'Alsace", 'fr:choucroutes-garnies'),
        ('Choucroute Garnie', 'fr:choucroutes-garnies'),
        ('Choucroute garnie Auchan', 'fr:choucroutes-garnies'),
        ('1898 - Choucroute royale au Riesling, mitonné doucement', 'fr:choucroutes-garnies'),
        ('1898 - Choucroute royale au Riesling, mitonné doucement', 'fr:choucroutes-royales'),
        ('Choucroute garnie royale', 'fr:choucroutes-garnies'),
        ('Choucroute Royale', 'fr:choucroutes-garnies'),
        ('Choucroute royale au Riesling', 'fr:choucroutes-garnies'),
        ('Coquillettes completes', 'fr:pates-seches-completes'),
        ('Coquillettes', 'fr:coquillettes'),
        ('Coquillettes', 'fr:coquillettes-de-ble-dur'),
        ('Coquillettes Bio', 'fr:coquillettes'),
        ('Coquillettes Bio', 'fr:coquillettes-de-ble-dur'),
        ('Pâtes Coquillettes', 'fr:coquillettes'),
        ('Pâtes Coquillettes', 'fr:coquillettes-de-ble-dur'),
        ('Coquillettes de riz', 'fr:coquillettes'),
        ('Coquillettes (Maxi Format)', 'fr:coquillettes'),
        ('Coquillettes (Maxi Format)', 'fr:coquillettes-de-ble-dur'),
        ('Pâte coquillettes', 'fr:coquillettes'),
        ('Pâte coquillettes', 'fr:coquillettes-de-ble-dur'),
        ('Spaghetti de riz', 'fr:coquillettes'),
        ('Coquillettes complètes', 'fr:pates-seches-completes'),
        ('Coquillette 1 kg', 'fr:coquillettes'),
        ('Coquillette 1 kg', 'fr:coquillettes-de-ble-dur'),
        ('Pâtes Coquillettes cuisson 3 min', 'fr:coquillettes'),
        ('Pâtes Coquillettes cuisson 3 min', 'fr:coquillettes-de-ble-dur'),
        ('Coquillettes au blé complet', 'fr:pates-seches-completes'),
        ('Al dente en 3 minutes Coquillettes cuisson rapide (lot de 2)', 'fr:coquillettes'),
        ('Al dente en 3 minutes Coquillettes cuisson rapide (lot de 2)', 'fr:coquillettes-de-ble-dur'),
        ('Coquillette', 'fr:coquillettes'),
        ('Coquillette', 'fr:coquillettes-de-ble-dur'),
        ("Coquillettes issues de l'agriculture biologique", 'fr:coquillettes'),
        ("Coquillettes issues de l'agriculture biologique", 'fr:coquillettes-de-ble-dur'),
        ('Coquillettes au beurre', 'fr:coquillettes-au-beurre'),
        ('Beaufort au lait cru', 'fr:beaufort'),
        ('Beaufort aop', 'fr:beaufort'),
        ('Beaufort', 'fr:sables-sales'),
        ('BEAUFORT', 'fr:sables-sales'),
        ('BEAUFORT AOP', 'fr:beaufort'),
        ('Beaufort AOP', 'fr:beaufort'),
        ('Beaufort été', 'fr:beaufort'),
        ('Beaufort ete', 'fr:beaufort'),
        ('beaufort AOP lait cru', 'fr:beaufort'),
        ('Beaufort au lait cru AOP', 'fr:beaufort'),
        ('Pâte Brisée', 'fr:pates-brisees'),
        ('Pâte Brisée Pur Beurre', 'fr:pates-brisees'),
        ('Tarte en or brisée', 'fr:pates-brisees'),
        ('Pâte brisée', 'fr:pates-brisees'),
        ('Pâte brisée, trésor de grand-mère', 'fr:pates-brisees'),
        ('Pâte brisée sans additif', 'fr:pates-brisees'),
        ('brisée', 'fr:pates-brisees'),
        ('pâte brisée', 'fr:pates-brisees'),
        ('Pâtes brisées pur beurre x2 + 1', 'fr:pates-brisees'),
        ('Pâte brisée sans gluten', 'fr:pates-brisees'),
        ('Pâte brisée sans gluten', 'fr:sans-gluten'),
        ('Pâte brisée sans gluten', 'fr:sans-lactose'),
        ('Pâtes brisées x3', 'fr:pates-brisees'),
        ('Pate brisée', 'fr:pates-brisees'),
        ('Tapenade Noire', 'fr:tapenades-noires'),
        ('Tapénade Noire', 'fr:tapenades-noires'),
        ('Les Tartinables (Thon Olives, Tomates Marinées et Poivrons)', 'fr:tapenades-noires'),
        ("Les Tartinables (Sardines & Tapenade d'Olives)", 'fr:rillettes-de-sardine'),
        ("Les Tartinables (Sardines & Tapenade d'Olives)", 'fr:tapenades-noires'),
        ('Paté de aceituna negra con almendras', 'fr:tapenades-noires'),
        ('Tapenade noire facon des bergers Varois', 'fr:tapenades-noires'),
        ('Tapenade noire', 'fr:tapenades-noires'),
        ('Tapenade noire Coudène', 'fr:tapenades-noires'),
        ('Tapenade noire facon des bergers Varois AU BEC FIN', 'fr:tapenades-noires'),
        ('Tapenade', 'fr:tapenades-noires'),
        ('la tapenade noire', 'fr:tapenades-noires'),
        ("Tapenade d'olives noires", 'fr:tapenades-noires'),
        ('Tapenade noire à la provençale', 'fr:tapenades-noires'),
        ('Tapenade noire à la provençale', 'fr:preparation-toast'),
        ('Crème Dessert Saveur Vanille', 'fr:cremes-dessert-vanille'),
        ('Crème dessert aromatisée saveur vanille', 'fr:cremes-dessert-vanille'),
        ('Crème dessert aromatisée saveur vanille', 'fr:desserts-lactes-a-la-vanille'),
        ('Crème dessert Saveur vanille', 'fr:cremes-dessert-vanille'),
        ('Crème dessert saveur vanille', 'fr:cremes-dessert-vanille'),
        ('Paturette Saveur Vanille', 'fr:cremes-dessert-vanille'),
        ('Crème dessert saveur Vanille', 'fr:cremes-dessert-vanille'),
        ('Danette vanille', 'fr:cremes-dessert-vanille'),
        ('Danet Vainilla', 'fr:cremes-dessert-vanille'),
        ('Danette Saveur Vanille', 'fr:cremes-dessert-vanille'),
        ('Danette Saveur vanille', 'fr:cremes-dessert-vanille'),
        ('Crème Dessert saveur Vanille', 'fr:cremes-dessert-vanille'),
        ('Goûters Laitiers vanille en gourdes', 'fr:cremes-dessert-vanille'),
        ('Goûters Laitiers vanille en gourdes', 'fr:desserts-lactes-a-la-vanille'),
        ('Goûters laitiers vanille', 'fr:cremes-dessert-vanille'),
        ('Vinaigrette Nature allégée en matières grasses', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ("Vinaigrette allégée en matières grasses à l'échalote", 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ("Sauce Salade Légère Moutarde à L'ancienne Lesieur", 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ("Vinaigrette moutarde à l'ancienne", 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('Vinaigrette légère tapenade verte Puget', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('Sauce salade nature à la moutarde de Dijon légère', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('Vinaigrette Nature Carrefour', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('Vinaigrette légère', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ("Vinaigrette légère, vinaigre balsamique de Modène et pointe d'orange", 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('Vinaigrette stylesse -45%', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ("Vinaigrette Légère Huile D'olive Et Tomates Séchées", 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('Vinaigrette Légère Moutarde', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('Vinaigrette Allégée en Matières Grasses Nature', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('La Vinaigrette nature (25,5 % MG) ', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ('Vinaigrette balsamique Tomates séchées', 'fr:vinaigrettes-allegees-en-matieres-grasses'),
        ("Vinaigrette légère - Huile d'Olive et Pointe d'Olive Noire", 'fr:vinaigrettes-allegees-en-matieres-grasses'),
]

def add_food_in_db():
    ''' 
    For each category of list_of_categories,
    add in the database a certain number of foods
    with relevent informations
    '''
    for category in list_of_categories:
        products = openfoodfacts.products.get_by_facets({
            'category': category,
            'country': 'france',
            'json':'1',
            })
        for product in products:
            try:
                f = Food(
                    name=product['product_name'], 
                    nutriscore=product['nutriscore_grade'],
                    picture_url=product['image_front_url'],
                    off_url=product['url'],
                    sugar_100g=product['nutriments']['sugars_100g'],
                    salt_100g=product['nutriments']['salt_100g'],
                    carbohydrates_100g=product['nutriments']['carbohydrates_100g'],
                    sodium_100g=product['nutriments']['sodium_100g'],
                    saturated_fat_100g=product['nutriments']['saturated-fat_100g'],
                    proteins_100g=product['nutriments']['proteins_100g'],
                    fat_100g=product['nutriments']['fat_100g'],
                    )
                f.save()
                print(product['product_name'], ' added')
            except:
                pass

# dont use it if you use the pre filled fc list
def fc_list_filler():
    '''
    look at foods in our database and their respective category
    in OFF's database, then fills fc_list with the foods and their
    respective category in the form of tuples
    '''
    for item in Food.objects.all():
        search_result = openfoodfacts.products.advanced_search({
        "search_terms":item.name,
        'fat':item.fat_100g,
        "country":"France",
        'json':'1',
        })
        try:
            for tag in search_result['products'][0]['categories_tags']:
                if tag.startswith('fr'):
                    fc_list.append((item.name, tag))
                    print(item.name, ' ', tag)
        except KeyError:
            print('key error')

def add_categories_in_db():
    '''
    add each category from fc list in the database 'category'
    '''
    # for item in fc_list:
    for item in pre_filled_fc_list:    
        try:
            c = Category(name=item[1])
            c.save()
            print(item[1], ' added')
        except:
            pass

def fills_fc_database():
    '''
    Add in Food_category database the id of 
    the foods and their category
    '''
    # for item in fc_list:
    for item in pre_filled_fc_list:
        try:
            food_id = Food.objects.filter(name=item[0])[0]
            category_id = Category.objects.filter(name=item[1])[0]
            fc = Food_category(food=food_id, category=category_id)
            fc.save()
            print('food_id : {}, category_id : {}, added'.format(food_id, category_id))
        except:
            pass

add_food_in_db()
fc_list_filler()
add_categories_in_db()
fills_fc_database()